### ISSUE TITLE
[BUG]Identifier非唯一

### ISSUE THREAD

**Issue by Kevin-Ben** [Sansui233/proxypool#39]
```
  -
    name: v1|新加坡|C|8台负载
    type: ss
    server: k3.xxx.xyz
    port: 41321
    cipher: aes-128-gcm
    password: 234343
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: 61717d7660726d2b33627f7566.office.com
  -
    name: v1|新加坡|B|7台负载
    type: ss
    server: k2.xxx.xyz
    port: 41321
    cipher: aes-128-gcm
    password: 234343
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: 61717d7660726d2b33627f7561.office.com

```

这是2台节点，被识别成一个。

**Comment by Kevin-Ben** [comment]
plugin-opts.host不一样

**Comment by Kevin-Ben** [comment]
```
type Shadowsocks struct {
	Base
	Password   string                 `yaml:"password" json:"password"`
	Cipher     string                 `yaml:"cipher" json:"cipher"`
	Plugin     string                 `yaml:"plugin" json:"plugin"`
	PluginOpts map[string]interface{} `yaml:"plugin-opts" json:"plugin-opts"`
}
```
这个也需要修改下

**Comment by Sansui233** [comment]
上述转换后的identifier分别为
`
k3.xxx.xyz:41321234343
k2.xxx.xyz:41321234343
`
并非相同的标识符。

另外代理最低使用进程（主机+端口号）作为标识，插件选项在区分代理上并无意义。换言之，一个主机可以运行多个进程，一个进程可以有多个端口号，但同一个端口号只能运行一个代理（如果上述有错误可以指正）

**Comment by Kevin-Ben** [comment]
```yaml
proxies:
  -
    name: v2|亚洲|C|混合负载|无敌主力
    type: ss
    server: k3.fastfrog.top
    port: 41322
    cipher: aes-128-gcm
    password: c30b999910f5
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: 61717f7060706d7d67627f7569.office.com
  -
    name: v2|亚洲|C|混合负载|视频主力
    type: ss
    server: k3.fastfrog.top
    port: 41322
    cipher: aes-128-gcm
    password: c30b99sss
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: 61717f7060706d7d67627776.office.com
```
go解析忽略了`Plugin `以及`PluginOpts`,上面通过 `plugin-opts.host`识别为2个ss
